#!/bin/zsh
# =============================================================================
# kopia-launchd-setup.sh
# Dynamically sets up launchd agents for all kopia repositories found on
# this machine. Discovers config files automatically — no hardcoded paths.
#
# Usage:
#   chmod +x kopia-launchd-setup.sh
#   ./kopia-launchd-setup.sh
#
# Each discovered repository gets:
#   - A wrapper script (run-kopia-<name>.sh) with timestamped log output
#   - A launchd plist installed to ~/Library/LaunchAgents/
#   - A schedule of 9am, 1pm, 5pm, 9pm, staggered 15 min per repo
# =============================================================================

set -euo pipefail
setopt KSH_ARRAYS  # 0-based array indexing

KOPIA_CONFIG_DIR="$HOME/Library/Application Support/kopia"
LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
LOG_DIR="$HOME/Library/Logs"
WRAPPER_DIR="$HOME/.local/bin"

# Schedule hours and per-repo stagger offsets (minutes)
SCHEDULE_HOURS=(9 13 17 21)
STAGGER_MINUTES=(0 15 30 45)

# ── Locate kopia binary ──────────────────────────────────────────────────
echo "==> Locating kopia binary..."

KOPIA_BIN=""

for candidate in \
    "$(which kopia 2>/dev/null || true)" \
    "/opt/homebrew/bin/kopia" \
    "/usr/local/bin/kopia" \
    "/Applications/KopiaUI.app/Contents/Resources/kopia" \
    "/Applications/KopiaUI.app/Contents/MacOS/kopia"
do
    if [[ -x "$candidate" ]]; then
        KOPIA_BIN="$candidate"
        break
    fi
done

if [[ -z "$KOPIA_BIN" ]]; then
    KOPIA_BIN=$(find /Applications/KopiaUI.app -name "kopia" -type f -perm +111 2>/dev/null | head -1 || true)
fi

if [[ -z "$KOPIA_BIN" ]]; then
    echo "ERROR: Could not find kopia binary."
    echo "  Install via Homebrew:  brew install kopia"
    echo "  Or locate manually:    find /Applications/KopiaUI.app -name 'kopia' -type f"
    exit 1
fi

echo "    Found: $KOPIA_BIN"
echo "    Version: $("$KOPIA_BIN" --version 2>&1 | head -1)"

# ── Ensure wrapper script destination exists ─────────────────────────────
mkdir -p "$WRAPPER_DIR"

# ── Discover kopia config files ──────────────────────────────────────────
echo ""
echo "==> Discovering kopia repositories in $KOPIA_CONFIG_DIR ..."

CONFIG_FILES=()
while IFS= read -r f; do
    CONFIG_FILES+=("$f")
done < <(find "$KOPIA_CONFIG_DIR" -maxdepth 1 -name "*.config" -type f | sort)

if [[ ${#CONFIG_FILES[@]} -eq 0 ]]; then
    echo "ERROR: No kopia config files found in $KOPIA_CONFIG_DIR"
    echo "  Connect at least one repository in KopiaUI first."
    exit 1
fi

if [[ ${#CONFIG_FILES[@]} -gt ${#STAGGER_MINUTES[@]} ]]; then
    echo "ERROR: Found ${#CONFIG_FILES[@]} repos but only ${#STAGGER_MINUTES[@]} stagger slots defined."
    echo "  Add more entries to STAGGER_MINUTES in this script."
    exit 1
fi

echo "    Found ${#CONFIG_FILES[@]} config(s):"
for f in "${CONFIG_FILES[@]}"; do
    DESC=$(python3 -c "
import json, sys
try:
    d = json.load(open(sys.argv[1])).get('description', '').strip()
    print(d if d else '')
except Exception:
    print('')
" "$f")
    if [[ -n "$DESC" ]]; then
        echo "      $(basename "$f")  →  \"$DESC\""
    else
        echo "      $(basename "$f")"
    fi
done

# ── Generate wrapper scripts and plists ──────────────────────────────────
echo ""
echo "==> Generating agents..."

GENERATED_PLIST_FILES=()
GENERATED_CONFIG_FILES=()
GENERATED_CONFIG_NAMES=()
GENERATED_SLUGS=()

for (( i=0; i<${#CONFIG_FILES[@]}; i++ )); do
    CONFIG_FILE="${CONFIG_FILES[$i]}"

    # Use description from config JSON as the friendly name, fall back to filename
    DESCRIPTION=$(python3 -c "
import json, sys
try:
    d = json.load(open(sys.argv[1])).get('description', '').strip()
    print(d if d else '')
except Exception:
    print('')
" "$CONFIG_FILE")

    if [[ -n "$DESCRIPTION" ]]; then
        CONFIG_NAME="$DESCRIPTION"
    else
        CONFIG_NAME=$(basename "$CONFIG_FILE" .config)
    fi

    # Sanitize name for use in labels and filenames
    SLUG=$(echo "$CONFIG_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')

    LABEL="com.kopia.backup.$SLUG"
    PLIST_FILE="$LAUNCH_AGENTS_DIR/$LABEL.plist"
    WRAPPER_FILE="$WRAPPER_DIR/run-kopia-$SLUG.sh"
    LOG_FILE="$LOG_DIR/kopia-$SLUG.log"
    MINUTE=${STAGGER_MINUTES[$i]}

    # Generate wrapper script
    cat > "$WRAPPER_FILE" << WRAPPER
#!/bin/bash
# Auto-generated by kopia-launchd-setup.sh — do not edit manually.
# Re-run kopia-launchd-setup.sh to regenerate.

KOPIA_BIN="$KOPIA_BIN"
CONFIG="$CONFIG_FILE"

echo "=== \$(date '+%Y-%m-%d %H:%M:%S') Starting kopia snapshot ($CONFIG_NAME) ==="

"\$KOPIA_BIN" snapshot create --all \\
    --config-file "\$CONFIG" \\
    --log-level=info

EXIT_CODE=\$?

if [ \$EXIT_CODE -eq 0 ]; then
    echo "=== \$(date '+%Y-%m-%d %H:%M:%S') Snapshot completed successfully ==="
else
    echo "=== \$(date '+%Y-%m-%d %H:%M:%S') Snapshot FAILED (exit code: \$EXIT_CODE) ==="
fi

exit \$EXIT_CODE
WRAPPER
    chmod +x "$WRAPPER_FILE"

    # Generate plist
    cat > "$PLIST_FILE" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>

    <!-- Auto-generated for config: $CONFIG_NAME -->

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$WRAPPER_FILE</string>
    </array>

    <!-- 9:00am, 1:00pm, 5:00pm, 9:00pm + ${MINUTE}min stagger -->
    <key>StartCalendarInterval</key>
    <array>
        <dict><key>Hour</key><integer>9</integer><key>Minute</key><integer>$MINUTE</integer></dict>
        <dict><key>Hour</key><integer>13</integer><key>Minute</key><integer>$MINUTE</integer></dict>
        <dict><key>Hour</key><integer>17</integer><key>Minute</key><integer>$MINUTE</integer></dict>
        <dict><key>Hour</key><integer>21</integer><key>Minute</key><integer>$MINUTE</integer></dict>
    </array>

    <key>StandardOutPath</key>
    <string>$LOG_FILE</string>
    <key>StandardErrorPath</key>
    <string>$LOG_FILE</string>

    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
PLIST

    GENERATED_PLIST_FILES+=("$PLIST_FILE")
    GENERATED_CONFIG_FILES+=("$CONFIG_FILE")
    GENERATED_CONFIG_NAMES+=("$CONFIG_NAME")
    GENERATED_SLUGS+=("$SLUG")

    echo "    $LABEL  (schedule: :$MINUTE past each hour)"
done

# ── Validate plists ───────────────────────────────────────────────────────
echo ""
echo "==> Validating plist XML..."
for PLIST_FILE in "${GENERATED_PLIST_FILES[@]}"; do
    plutil "$PLIST_FILE" && echo "    $(basename "$PLIST_FILE") OK"
done

# ── Load agents ───────────────────────────────────────────────────────────
echo ""
echo "==> Loading launchd agents..."
for PLIST_FILE in "${GENERATED_PLIST_FILES[@]}"; do
    launchctl unload "$PLIST_FILE" 2>/dev/null || true
    launchctl load "$PLIST_FILE"
    echo "    Loaded: $(basename "$PLIST_FILE" .plist)"
done

# ── Verify agents are registered ─────────────────────────────────────────
echo ""
echo "==> Verifying agents..."
launchctl list | grep com.kopia || echo "WARNING: Agents not found in launchctl list"

# ── Optional: run a test backup now ──────────────────────────────────────
echo ""
echo -n "==> Run a test backup NOW against all repos? [y/N] "
read -r RUN_TEST
if [[ "$RUN_TEST" =~ ^[Yy]$ ]]; then
    for (( i=0; i<${#GENERATED_CONFIG_FILES[@]}; i++ )); do
        echo ""
        echo "--- Starting test snapshot (${GENERATED_CONFIG_NAMES[$i]}) ---"
        "$KOPIA_BIN" snapshot create --all \
            --config-file "${GENERATED_CONFIG_FILES[$i]}" \
            --log-level=info
        echo "--- ${GENERATED_CONFIG_NAMES[$i]} snapshot complete ---"
    done
fi

# ── Summary ───────────────────────────────────────────────────────────────
echo ""
echo "==> Done!"
echo ""
echo "    Agents installed:"
for (( i=0; i<${#GENERATED_SLUGS[@]}; i++ )); do
    echo "      com.kopia.backup.${GENERATED_SLUGS[$i]}  →  :${STAGGER_MINUTES[$i]} past 9am/1pm/5pm/9pm"
done
echo ""
echo "    Logs: $LOG_DIR/kopia-*.log"
echo ""
echo "    To check status:     launchctl list | grep com.kopia"
echo "    To trigger manually: launchctl start com.kopia.backup.<name>"
echo "    To unload:           launchctl unload $LAUNCH_AGENTS_DIR/com.kopia.backup.<name>.plist"
